### ISSUE TITLE
Translat error

### ISSUE THREAD

**Issue by Huayuluoshi** [uiYzzi/Yolx#3]
Advanced?先进的?
![截图 2024-03-12 14-18-56](https://github.com/uiYzzi/Yolx/assets/117527694/3b73e1a6-3220-4189-a412-be101beee8df)

**Comment by uiYzzi** [comment]
[💬 Corrected Chinese translation](https://github.com/uiYzzi/Yolx/commit/8a5fc9416b1d14e272a191e72f98517417d5e35b)
![图片](https://github.com/uiYzzi/Yolx/assets/40852301/0095a9b0-4298-4beb-ac4c-297d279ab2c5)
