### ISSUE TITLE
如何设置aria2远程下载？

### ISSUE THREAD

**Issue by liao666brant** [uiYzzi/Yolx#4]
想要知道如何配置aria2远程下载，因为软件的设置相对于其他aria2 GUI设置RPC有些奇怪？
我尝试配置之后下载似乎没有反应，希望能够提供配置说明。
下面是我的设置截图：
![image](https://github.com/uiYzzi/Yolx/assets/50171055/bde13f4e-aa02-4ed6-af4b-5e126e41be20)

**Comment by uiYzzi** [comment]
这里是配置aria2后端的rpc参数，软件目前暂时还不支持连接到其他远程aria2服务器，不过这个功能在规划中，需要等待后续开发。
